language: cpp

compiler:
- gcc
- clang

install:
- sudo apt-get install libboost-all-dev

script:
- mkdir -p build && cd build && cmake ../test && make && cd ..
- mkdir -p build-runningstats && cd build-runningstats && cmake ../test/runningstats && make && cd ..

after_failure:
- cmake --version
- gcc --version
- g++ --version
- clang --version
